### ISSUE TITLE
drush dl is deprecated for Drush 9

### ISSUE THREAD

**Issue by rajnishmsrit** [carlosreig/docker-lamp#19]
L3 in scripts/install_drupal8.sh downloads drush 9 and therefore it breaks the L5 command as `drush dl` used is deprecated in Drush 9.

PR and approach for the issue: https://github.com/carlosreig/docker-lamp/pull/18

Reference: https://drushcommands.com/drush-9x/pm/pm:download/

**Comment by carlosreig** [comment]
PR #18  is merged. I closed the issue. Thanks!
