### ISSUE TITLE
Setup a volume to mysql databases

### ISSUE THREAD

**Issue by cleyan** [carlosreig/docker-lamp#8]
Hi
Great work with this files! I tried other configs and this is the first that really work for me

I'm starting to use docker o create a dev enviroment 

Now I want to use a persistent volume to store the mysql databases, do you know how can i do that? I added a volume on the docker-compose.yml file but I can't connect to database using the password defined on MYSQL_ROOT_PASSWORD constant

Thank you for your help and congrats for your work

Carlos

**Comment by carlosreig** [comment]
Hi Cleyan,

Sorry for the delay. I couldn't answer when I was notified about the issue and after that I completely forgot about that.

Thank you for using it :) I'm very happy that it suits for you!

For accessing the database you have to use the following credentials:
user: `root`
password: `123`

In addition, if you are trying to connect from the Apache's container (by using `./bash.sh` or `./root_bash.sh` scripts) you have to set MySQL's container hostname that is `db`.
So, if you want to connect to the database you can execute: `mysql -u root -p123 -hdb`.

Hope it helps. Please, let me know if you have more doubts :)

Have a nice day.
Carlos
